apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: first-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: first-deployment
  template:
    metadata:
      labels:
        app: first-deployment 
    spec:
      containers: 
      - name: first-container
        image: nginx:latest
        ports:
        - containerPort: 80 