# Prometheus Configuration for Microservices Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Service Registry
  - job_name: 'service-registry'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8761']
        labels:
          application: 'service-registry'

  # Gateway Service
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:6060']
        labels:
          application: 'gateway-service'

  # Auth Service
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:6061']
        labels:
          application: 'auth-service'

  # Access Management Service
  - job_name: 'access-management-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:6062']
        labels:
          application: 'access-management-service'

