apiVersion: v1
kind: ConfigMap
metadata:
  name: care-config
  namespace: care-system
  labels:
    app: care-system
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  EUREKA_SERVER: "http://service-registry.care-system.svc.cluster.local:8761/eureka"
  CONFIG_SERVER: "http://config-server.care-system.svc.cluster.local:8888"
  DATABASE_HOST: "postgres.care-system.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "cms_db"
  DATABASE_USERNAME: "postgres"
  JAVA_OPTS_BASE: "-Xmx512m -Xms256m"
  LOG_LEVEL: "INFO"
