apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
  labels:
    app: chatbot-service
  namespace: default
data:
  chatbot.identity-source: "RAIS"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/chatbot"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
